### ISSUE TITLE
Launcher v2

### ISSUE THREAD

**Issue by kanerogers** [richy486/SabbaticalArcade#1]
## Background
This issue tracks features for the new launcher.

## TODO
- [ ] Build minimal implementation
- [ ] Show loading indicator before game appears
- [ ] Have separate menu for shows, etc.
- [ ] Create an API for games list
